version: '3.4'

services:
  registration.clientwebapi:
    image: registration
    build:
      context: .
      dockerfile: Sample/Reservation/v1/Registration/Registration.ClientWebApi/Dockerfile


  business.webapi:
    image: business
    build:
      context: .
      dockerfile: Sample/Reservation/v1/Business/Business.WebApi/Dockerfile

  

  workerrolecommandprocessor:
    image: workerrolecommandprocessor
    build:
      context: .
      dockerfile: Sample/Reservation/v1/WorkerRoleCommandProcessor/Dockerfile
