version: '3.4'

services:
  business.webapi:
    image: business
    build:
      context: .
      dockerfile: Sample/Reservation/Business.WebApi/Dockerfile

  registration.clientwebapi:
    image: registration
    build:
      context: .
      dockerfile: Sample/Reservation/Registration.ClientWebApi/Dockerfile

