version: '3.4'

services:
  business.webapi:
    image: business
    build:
      context: .
      dockerfile: Sample/Reservation/Business.WebApi/Dockerfile

  registration.clientwebapi:
    image: registration
    build:
      context: .
      dockerfile: Sample/Reservation/Registration.ClientWebApi/Dockerfile


  dockerdemo:
    image: dockerdemo
    build:
      context: .
      dockerfile: Sample/DockerDemo/Dockerfile


  workerrolecommandprocessor:
    image: workerrolecommandprocessor
    build:
      context: .
      dockerfile: Sample/Reservation/WorkerRoleCommandProcessor/Dockerfile

