// <auto-generated />
using MAR.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace MAR.Infra.Data.Migrations
{
    [DbContext(typeof(MARContext))]
    [Migration("20180609170300_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("MAR.Infra.Data.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("EquivalentLocaleName");

                    b.Property<string>("RegionString");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Branding", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessId");

                    b.Property<string>("LogoURL");

                    b.Property<string>("PageColor1");

                    b.Property<string>("PageColor2");

                    b.Property<string>("PageColor3");

                    b.Property<string>("PageColor4");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("Branding");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Business", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.BusinessAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessId");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("ForeignZip");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Street2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("BusinessAddress");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.BusinessContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessId");

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<string>("Phone3");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("BusinessContact");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Location", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.LocationAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("ForeignZip");

                    b.Property<double>("Latitude");

                    b.Property<string>("LocationId");

                    b.Property<double>("Longitude");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Street2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationAddress");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.LocationContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("LocationId");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<string>("Phone3");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationContact");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.LocationImage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageURL");

                    b.Property<string>("LocationId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationImage");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Staff", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<string>("BusinessId");

                    b.Property<string>("DisplayName");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsMale");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("ForeignZip");

                    b.Property<string>("PostalCode");

                    b.Property<string>("StaffId");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Street2");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffAddress");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<string>("Phone3");

                    b.Property<string>("StaffId");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffContact");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffLoginCredential", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("StaffId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffLoginCredential");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffLoginLocation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LocationId");

                    b.Property<string>("StaffId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffLoginLocation");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.TimeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.Property<string>("StandardName");

                    b.HasKey("Id");

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Branding", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Business", "Business")
                        .WithOne("Branding")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.Branding", "BusinessId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.BusinessAddress", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Business", "Business")
                        .WithOne("Address")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.BusinessAddress", "BusinessId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.BusinessContact", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Business", "Business")
                        .WithOne("Contact")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.BusinessContact", "BusinessId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Location", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Business", "Business")
                        .WithMany("Locations")
                        .HasForeignKey("BusinessId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.LocationAddress", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Location", "Location")
                        .WithOne("Address")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.LocationAddress", "LocationId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.LocationContact", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Location", "Location")
                        .WithOne("Contact")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.LocationContact", "LocationId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.LocationImage", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Location", "Location")
                        .WithMany("AdditionalLocationImages")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.Staff", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Business", "Business")
                        .WithMany("Staffs")
                        .HasForeignKey("BusinessId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffAddress", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Staff", "Staff")
                        .WithOne("Address")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.StaffAddress", "StaffId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffContact", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Staff", "Staff")
                        .WithOne("Contact")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.StaffContact", "StaffId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffLoginCredential", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Staff", "Staff")
                        .WithOne("LoginCredential")
                        .HasForeignKey("MAR.Infra.Data.Models.Security.StaffLoginCredential", "StaffId");
                });

            modelBuilder.Entity("MAR.Infra.Data.Models.Security.StaffLoginLocation", b =>
                {
                    b.HasOne("MAR.Infra.Data.Models.Security.Location", "Location")
                        .WithMany("StaffLoginLocations")
                        .HasForeignKey("LocationId");

                    b.HasOne("MAR.Infra.Data.Models.Security.Staff", "Staff")
                        .WithMany("StaffLoginLocations")
                        .HasForeignKey("StaffId");
                });
#pragma warning restore 612, 618
        }
    }
}
