// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using Registration.Infra.Data.Context;
using System;

namespace Registration.Infra.Data.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    partial class ReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Registration.Domain.ReadModel.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("EquivalentLocaleName");

                    b.Property<string>("RegionString")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("RegionView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Branding", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("LogoURL");

                    b.Property<string>("PageColor1");

                    b.Property<string>("PageColor2");

                    b.Property<string>("PageColor3");

                    b.Property<string>("PageColor4");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("BrandingView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Location", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("LocationView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.LocationAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("ForeignZip");

                    b.Property<double>("Latitude");

                    b.Property<string>("LocationId");

                    b.Property<double>("Longitude");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Street2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationAddressView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.LocationContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("LocationId");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<string>("Phone3");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationContactView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.LocationImage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("ImageURL");

                    b.Property<string>("LocationId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationImageView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Staff", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Bio");

                    b.Property<string>("DisplayName");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsMale");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("StaffView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("ForeignZip");

                    b.Property<string>("PostalCode");

                    b.Property<string>("StaffId");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Street2");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffAddressView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<string>("Phone3");

                    b.Property<string>("StaffId");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffContactView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffLoginCredential", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Password");

                    b.Property<string>("StaffId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffLoginCredentialView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffLoginLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(32)");

                    b.Property<string>("StaffId");

                    b.Property<string>("LocationId");

                    b.HasKey("Id", "StaffId", "LocationId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffLoginLocationView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TenantView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.TenantAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("ForeignZip");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Street2");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantAddressView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.TenantContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<string>("Phone3");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantContactView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.TimeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired();

                    b.Property<string>("StandardName");

                    b.HasKey("Id");

                    b.ToTable("TimeZoneView");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Branding", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Tenant", "Tenant")
                        .WithOne("Branding")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.Branding", "TenantId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Location", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Tenant", "Tenant")
                        .WithMany("Locations")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.LocationAddress", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Location", "Location")
                        .WithOne("Address")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.LocationAddress", "LocationId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.LocationContact", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Location", "Location")
                        .WithOne("Contact")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.LocationContact", "LocationId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.LocationImage", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Location", "Location")
                        .WithMany("AdditionalLocationImages")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.Staff", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Tenant", "Tenant")
                        .WithMany("Staffs")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffAddress", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Staff", "Staff")
                        .WithOne("Address")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.StaffAddress", "StaffId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffContact", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Staff", "Staff")
                        .WithOne("Contact")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.StaffContact", "StaffId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffLoginCredential", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Staff", "Staff")
                        .WithOne("LoginCredential")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.StaffLoginCredential", "StaffId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.StaffLoginLocation", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Location", "Location")
                        .WithMany("StaffLoginLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Registration.Domain.ReadModel.Security.Staff", "Staff")
                        .WithMany("StaffLoginLocations")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.TenantAddress", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Tenant", "Tenant")
                        .WithOne("Address")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.TenantAddress", "TenantId");
                });

            modelBuilder.Entity("Registration.Domain.ReadModel.Security.TenantContact", b =>
                {
                    b.HasOne("Registration.Domain.ReadModel.Security.Tenant", "Tenant")
                        .WithOne("Contact")
                        .HasForeignKey("Registration.Domain.ReadModel.Security.TenantContact", "TenantId");
                });
#pragma warning restore 612, 618
        }
    }
}
