// <auto-generated />
using Business.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Business.Infra.Data.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20180612144323_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EquivalentLocaleName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RegionString")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Resource", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsLocatedAtAllLocations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceTypeId");

                    b.Property<string>("ScheduleId")
                        .HasColumnType("char(32)");

                    b.Property<int>("StatusId");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId")
                        .IsUnique();

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StatusId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ResourceLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(32)");

                    b.Property<string>("ResourceId")
                        .HasColumnType("char(32)");

                    b.Property<string>("LocationId")
                        .HasColumnType("char(32)");

                    b.HasKey("Id", "ResourceId", "LocationId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceLocation");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ResourceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ResourceStatus");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ResourceType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ResourceType");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Schedule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<int>("DaysVisible");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<bool>("IsCalendarSubscriptionAllowed");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("LayoutId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<string>("TenantId");

                    b.Property<int>("WeekdayStart");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.HasIndex("TenantId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ScheduleLayout", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("TenantId");

                    b.Property<int>("TimeZoneId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TimeZoneId");

                    b.ToTable("ScheduleLayout");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ScheduleLayoutTimeSlot", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<int>("AvailabilityCode");

                    b.Property<int>("DayOfWeek");

                    b.Property<string>("EndLabel")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Label")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LayoutId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("ScheduleLayoutTimeSlot");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Branding", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("LogoURL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PageColor1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PageColor2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PageColor3")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PageColor4")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Branding");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Location", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.LocationAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ForeignZip")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Latitude");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<double>("Longitude");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street2")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationAddress");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.LocationContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone3")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationContact");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.LocationImage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationImage");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Staff", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Bio");

                    b.Property<bool>("CanLoginAllLocations");

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsMale");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ForeignZip")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street2")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffAddress");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone3")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffContact");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffLoginCredential", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("StaffLoginCredential");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffLoginLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(32)");

                    b.Property<string>("StaffId")
                        .HasColumnType("char(32)");

                    b.Property<string>("LocationId")
                        .HasColumnType("char(32)");

                    b.HasKey("Id", "StaffId", "LocationId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffLoginLocation");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.TenantAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ForeignZip")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantAddress");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.TenantContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone3")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantContact");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.TimeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StandardName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TimeZone");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Resource", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.ResourceType", "ResourceType")
                        .WithOne("Resource")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Resource", "ResourceTypeId");

                    b.HasOne("Business.Infra.Data.ReadModel.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.HasOne("Business.Infra.Data.ReadModel.ResourceStatus", "Status")
                        .WithOne("Resource")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Resource", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ResourceLocation", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Location", "Location")
                        .WithMany("ResourceLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Business.Infra.Data.ReadModel.Resource", "Resource")
                        .WithMany("ResourceLocations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ResourceType", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Schedule", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.ScheduleLayout", "Layout")
                        .WithMany("Schedules")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ScheduleLayout", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("Business.Infra.Data.ReadModel.TimeZone", "TimeZone")
                        .WithMany("ScheduleLayouts")
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.ScheduleLayoutTimeSlot", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.ScheduleLayout", "Layout")
                        .WithMany("TimeSlots")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Branding", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithOne("Branding")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.Branding", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Location", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithMany("Locations")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.LocationAddress", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Location", "Location")
                        .WithOne("Address")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.LocationAddress", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.LocationContact", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Location", "Location")
                        .WithOne("Contact")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.LocationContact", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.LocationImage", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Location", "Location")
                        .WithMany("AdditionalLocationImages")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.Staff", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithMany("Staffs")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffAddress", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Staff", "Staff")
                        .WithOne("Address")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.StaffAddress", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffContact", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Staff", "Staff")
                        .WithOne("Contact")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.StaffContact", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffLoginCredential", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Staff", "Staff")
                        .WithOne("LoginCredential")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.StaffLoginCredential", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.StaffLoginLocation", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Location", "Location")
                        .WithMany("StaffLoginLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Business.Infra.Data.ReadModel.Security.Staff", "Staff")
                        .WithMany("StaffLoginLocations")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.TenantAddress", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithOne("Address")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.TenantAddress", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Infra.Data.ReadModel.Security.TenantContact", b =>
                {
                    b.HasOne("Business.Infra.Data.ReadModel.Security.Tenant", "Tenant")
                        .WithOne("Contact")
                        .HasForeignKey("Business.Infra.Data.ReadModel.Security.TenantContact", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
